- name: Create network infra on dragon
  hosts: dragon
  become: true
  roles:
    - pod
  tasks:
    - name: Remove route rule
      ansible.builtin.command:
        ip route del 10.1.0.0/16
      changed_when: false
      failed_when: false
    - name: Set the route on the node to reach the network namesapces on the other node
      ansible.builtin.command:
        ip route add 10.1.0.0/16 via 192.168.100.27 dev enp0s31f6
      changed_when: false
    - name: Enables Ip forwarding on the node
      ansible.builtin.command:
        sysctl -w net.ipv4.ip_forward=1
      changed_when: false
  vars:
    pod_containers:
      con1: 10.0.0.1
      con2: 10.0.0.2
    pod_br0: 10.0.0.10

- name: Create network infra on snake
  hosts: snake
  become: true
  roles:
    - pod
  tasks:
    - name: Remove route rule
      ansible.builtin.command:
        ip route del 10.0.0.0/16
      changed_when: false
      failed_when: false
    - name: Set the route on the node to rach the network namsapces on the other node
      ansible.builtin.command:
        ip route add 10.0.0.0/16 via 192.168.100.108 dev wlp1s0
      changed_when: false
    - name: Enables Ip forwarding on the node
      ansible.builtin.command:
        sysctl -w net.ipv4.ip_forward=1
      changed_when: false
  vars:
    pod_containers:
      con1: 10.1.0.3
      con2: 10.1.0.4
    pod_br0: 10.1.0.10

- name: Teardown
  tags: teardown
  hosts:
    - snake
    - dragon
  tasks:
    - name: Teardown
      ansible.builtin.command: echo "Teardown"
      changed_when: false
