- name: Create network infra on dragon
  hosts: dragon
  become: true
  roles:
    - pod
  tasks:
    - name: Remove route rule
      ansible.builtin.command:
        ip route del 10.1.0.0/16
      changed_when: false
      failed_when: false

    - name: Enables Ip forwarding on the node
      ansible.builtin.command:
        sysctl -w net.ipv4.ip_forward=1
      changed_when: false

    - name: Start the UDP tunnel in the background
      ansible.builtin.command:
        "socat -d -d UDP-LISTEN:11443,reuseaddr TUN:{{ tun0_cidr }},up"
      changed_when: false
      async: 600
      poll: 0
  vars:
    pod_containers:
      con1: 10.0.0.1
      con2: 10.0.0.2
    pod_br0: 10.0.0.10
    tun0_cidr: 10.1.0.100/16

- name: Create network infra on snake
  hosts: snake
  become: true
  roles:
    - pod
  tasks:
    - name: Remove route rule
      ansible.builtin.command:
        ip route del 10.0.0.0/16
      changed_when: false
      failed_when: false

    - name: Enables Ip forwarding on the node
      ansible.builtin.command:
        sysctl -w net.ipv4.ip_forward=1
      changed_when: false

    - name: Starts the UDP tunnel in the background
      ansible.builtin.command:
        "socat UDP:{{ pod_to_node_ip }}:11443 TUN:{{ tun0_cidr }},up"
      changed_when: false
      async: 600
      poll: 0
  vars:
    pod_containers:
      con1: 10.1.0.3
      con2: 10.1.0.4
    pod_br0: 10.1.0.10
    pod_to_node_ip: "{{ groups['dragon'][0] }}"
    tun0_cidr: 10.0.0.100/16



- name: Teardown snake
  tags: [never, teardown]
  hosts:
    - snake
  become: true
  vars:
    pod_containers:
      con1: 10.1.0.3
      con2: 10.1.0.4
    pod_br0: 10.1.0.10
  tasks:
    - name: Remove network namespaces
      ansible.builtin.command:
        ip netns delete {{ item }}
      with_items: "{{ pod_containers }}"
      failed_when: false
      changed_when: false

    - name: Remove network links
      ansible.builtin.command:
        "ip link delete {{ item }}0"
      with_items: "{{ pod_containers }}"
      changed_when: false
      failed_when: false

    - name: Remove bridge
      ansible.builtin.command:
        ip link delete br0
      changed_when: false
      failed_when: false

    - name: Remove virtual devices
      ansible.builtin.command: ip link delete {{ item }}
      with_items: "{{ pod_containers }}0"
      failed_when: false
      changed_when: false


- name: Teardown dragon
  tags: [never, teardown]
  hosts:
    - dragon
  become: true
  vars:
    pod_containers:
      con1: 10.0.0.2
      con2: 10.0.0.3
    pod_br0: 10.0.0.10
  tasks:
    - name: Remove network namespaces
      ansible.builtin.command:
        ip netns delete {{ item }}
      with_items: "{{ pod_containers }}"
      failed_when: false
      changed_when: false

    - name: Remove network links
      ansible.builtin.command:
        "ip link delete {{ item }}0"
      with_items: "{{ pod_containers }}"
      changed_when: false
      failed_when: false

    - name: Remove bridge
      ansible.builtin.command:
        ip link delete br0
      changed_when: false
      failed_when: false

    - name: Remove virtual devices
      ansible.builtin.command: ip link delete {{ item }}
      with_items: "{{ pod_containers }}0"
      failed_when: false
      changed_when: false
